
# Procesamiento de la Carta Marina de Córdoba 2017

## Descripción

Este notebook tiene como objetivo reconstruir y documentar el proceso de extracción de datos de la Carta Marina de Córdoba correspondiente a las elecciones de 2017.

El desarrollo se basa en el trabajo realizado en el repositorio **Carta Marina Córdoba 2017** de avdata99 (https://github.com/avdata99/carta-marina-2017/tree/master).

En esta etapa el trabajo se concentra exclusivamente en la Carta Marina 2017.

## Flujo de trabajo


1. PDF
2. TXT (pdftotext -layout)
3. CSV de mesas/escuelas/electores
4. Geolocalización de escuelas
5. CSV geolocalizado
6. Mapas y análisis


**Productos esperados**

- `LugaresDeVotacion-elecciones-2015.pdf`
- `carta-marina-cordoba-2015.txt`
- `escuelas-elecciones-2015-cordoba.csv`
- `escuelas-elecciones-2015-cordoba-clean.csv` (si requiere correcciones)

0. Dependencias

In [1]:
from google.colab import files
import pandas as pd
from pathlib import Path

In [2]:
!apt-get update -qq
!apt-get install -y -qq poppler-utils

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libpoppler-private-dev_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler-private-dev:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Preparing to unpack .../libpoppler-dev_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler-dev:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Preparing to unpack .../libpoppler118_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler118:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Selecting previously unselected package poppler-utils.
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.13) ...
Setting up libpoppler118:amd64 (22.02.0-2ubuntu0.13) ...
Setting up poppler-utils (22.02.0-2ubuntu0.13) ...
Setting up libpoppler-dev:amd64 (22.02.0-2ubuntu0.13) ...
Setting up libpoppler-private-dev:amd64 (22.02.0-2ubuntu0.13) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

#1. Carga del PDF

In [3]:
archivo = files.upload()

nombre_archivo = next(iter(archivo))

print(f"Archivo cargado: {nombre_archivo}")

Saving 2017.pdf to 2017.pdf
Archivo cargado: 2017.pdf

#2. PDF a TXT

In [4]:
nombre_txt = Path(nombre_archivo).with_suffix(".txt")

!pdftotext -layout "{nombre_archivo}" "{nombre_txt}"

print(f"Archivo generado: {nombre_txt}")

Archivo generado: 2017.txt

#3. TXT a CSV



```
Leer línea
    │
    ├── ¿Es un encabezado o número de página?
    │      └── Sí → ignorar
    │
    ├── ¿Es una sección?
    │      └── Sí → actualizar sección
    │
    ├── ¿Es un circuito?
    │      └── Sí → actualizar circuito e iniciar lectura de establecimientos
    │
    ├── ¿Es el resumen del circuito?
    │      └── Sí → finalizar lectura del circuito
    │
    ├── ¿Está vacía?
    │      └── Sí → ignorar
    │
    ├── ¿Estamos dentro de un circuito?
    │      └── No → continuar
    │
    └── Procesar establecimiento
           ├── Ignorar líneas "asociada a"
           ├── Reconstruir el nombre del establecimiento
           ├── Extraer mesas y electores
           ├── Validar continuidad de mesas
           └── Guardar registro
```

##Inspeccion del TXT

In [5]:
path = f"/content/{nombre_txt}"

with open(path, "r", encoding="utf-8") as f:
    raw = f.read()

lines = raw.splitlines()

print(f"Cantidad total de líneas: {len(lines)}")
print("\nPrimeras 10 líneas:\n")

for i, linea in enumerate(lines[:10], start=1):
    print(i, repr(linea))
print ("...")
print ("...")
print ("...")
print ("...")
for i, linea in enumerate(raw.splitlines()[-10:], start=len(raw.splitlines())-9):
    print(i, repr(linea))

Cantidad total de líneas: 3951

Primeras 10 líneas:

1 '                                        DISTRITO CORDOBA'
2 '                                           ELECCIONES 2017'
3 '                           Informe de Establecimientos,Mesas y Electores Habilitados'
4 ''
5 ''
6 ''
7 ''
8 'Sección 1 - CAPITAL'
9 ''
10 ' Circuito   1 - SECCIONAL PRIMERA                                   Cant Mesas   Mesas desde / hasta Cant Electores'
...
...
...
...
3942 '                  RESUMEN DEL DISTRITO:                 CORDOBA'
3943 '                  Establecimientos Habilitados:                   1.211'
3944 '                  Mesas Habilitadas:                              8.649'
3945 '                  Electores Habilitados:                      2.884.358'
3946 ''
3947 ''
3948 ''
3949 ''
3950 '                                                                                              Página 70 de 70'
3951 ''

In [6]:
print("Saltos de línea \\n:", raw.count("\n"))
print("Saltos de página \\f:", raw.count("\f"))

print("Con split('\\n'):", len(raw.split("\n")))
print("Con splitlines():", len(raw.splitlines()))

Saltos de línea \n: 3881
Saltos de página \f: 70
Con split('\n'): 3882
Con splitlines(): 3951

##Inicialización de variables

In [26]:
# =====================================
# Inicialización de variables del parser
# =====================================

# Sección electoral (equivale al departamento de la provincia)
seccion_nro = 0
seccion_name = ""

# Circuito electoral dentro de la sección.
# Puede contener letras (ej.: 4A, 4B, 4C), por eso se almacena como texto.
circuito_nro = ""
circuito_name = ""

# Estado actual del parser.
# Cuando vale "escuelas", las líneas leídas corresponden a establecimientos.
imin = ""

# Contador de líneas procesadas del archivo TXT.
cnt = 0

# Contador de errores (heredado del parser original).
errores = 0

# Lista donde se almacenan todos los establecimientos extraídos.
# Cada elemento es un diccionario con la información de un establecimiento.
escuelas = []

# Registra las discontinuidades detectadas en la numeración de mesas.
# Se utiliza como control de calidad, pero no interrumpe la ejecución.
discontinuidades = []

# Última mesa procesada.
# Permite verificar que la numeración de mesas sea continua.
last_mesa = 0

# ============================
# Variables de diagnóstico
# ============================

# Cantidad de números de página ignorados.
paginas_ignoradas = 0

# Cantidad de encabezados "DISTRITO CORDOBA" ignorados.
distritos_ignorados = 0

# Cantidad de encabezados "ELECCIONES 2015" ignorados.
elecciones_ignoradas = 0

# Cantidad de encabezados "Informe de Establecimientos" ignorados.
informes_ignorados = 0

# Almacena las filas que no pudieron procesarse correctamente,
# junto con la información necesaria para su revisión.
filas_con_error = []

print(f"Contador inicial: {cnt}")

Contador inicial: 0

##Ciclo for

In [27]:
for linea in lines:
    cnt += 1

    # Ignorar número de página
    if "Página" in linea:
        paginas_ignoradas += 1
        continue

    # Ignorar encabezados
    if linea.strip() == "DISTRITO CORDOBA":
        distritos_ignorados += 1
        continue

    if "ELECCIONES 20" in linea:
        elecciones_ignoradas += 1
        continue

    if "Informe de Establecimientos" in linea:
        informes_ignorados += 1
        continue

    # Detectar sección
    if linea.startswith("Sección "):
        contenido = linea.removeprefix("Sección ").strip()
        partes = contenido.split("-", 1)

        seccion_nro = int(partes[0].strip())
        seccion_name = partes[1].strip()

        imin = ""
        continue

    # Detectar circuito
    if linea.startswith(" Circuito"):
        contenido = linea.removeprefix(" Circuito").strip()
        partes = contenido.split("-", 1)

        circuito_nro = partes[0].strip()

        # En la misma línea aparecen los títulos de otras columnas
        partes_nombre = partes[1].split("       ")
        circuito_name = partes_nombre[0].strip()

        imin = "escuelas"
        continue

    # Detectar el final del listado de escuelas
    # Las líneas vacías se ignoran, pero no cierran el circuito
    if linea == "":
       continue

    # Solo el resumen cierra realmente el circuito
    if linea.startswith("Resúmen del Circuito"):
        imin = ""
        continue

    # Procesar escuelas
    if imin == "escuelas":
        partes = linea.split("    ")

        # Conservar solo fragmentos con contenido
        datos = [x.strip() for x in partes if x.strip() != ""]

        print(f"{cnt} -- {datos}")

        if len(datos) == 1 and "asociada a" in datos[0]:
            continue



        establecimiento = " ".join(datos[:-3])
        cant_mesas = int(datos[-3])

        rango_mesas = datos[-2].split(" a ")
        mesa_desde = int(rango_mesas[0])
        mesa_hasta = int(rango_mesas[1])


        if mesa_desde != last_mesa + 1:
            discontinuidades.append({
              "linea": cnt,
              "esperada": last_mesa + 1,
              "encontrada": mesa_desde,
              "establecimiento": establecimiento
          })
            #raise ValueError(
                #f"Mesa inválida en línea {cnt}: "
                #f"empieza en {mesa_desde}, "
                #f"pero la anterior terminó en {last_mesa}"
            #)

        last_mesa = mesa_hasta

        cant_electores = int(datos[-1].replace(".", ""))

        elem = {
            "seccion_nro": seccion_nro,
            "seccion_name": seccion_name,
            "circuito_nro": circuito_nro,
            "circuito_name": circuito_name,
            "establecimiento": establecimiento.replace(",", "."),
            "cant_mesas": cant_mesas,
            "desde": mesa_desde,
            "hasta": mesa_hasta,
            "electores": cant_electores,
        }

        escuelas.append(elem)
        print(f"Contador inicial: {cnt}")

11 -- ['CENTRO EDUC.NIVEL MEDIO ADULTO - DEAN FUNES 417', '7', '00001 a 00007', '2.401']
Contador inicial: 11
12 -- ['ESC NUESTRA SEÑORA DEL HUERTO - BELGRANO 269', '12', '00008 a 00019', '4.116']
Contador inicial: 12
13 -- ['COL NAC DE MONSERRAT - OBISPO TREJO 294', '18', '00020 a 00037', '6.158']
Contador inicial: 13
14 -- ['ESC SANTA TERESA DE JESUS - OBISPO TREJO Y SANABRIA 160', '10', '00038 a 00047', '3.420']
Contador inicial: 14
18 -- ['ESC JUAN BAUTISTA ALBERDI - GRAL PAZ 486', '18', '00048 a 00065', '6.145']
Contador inicial: 18
22 -- ['ESC JERONIMO LUIS DE CABRERA - SANTA ROSA 650', '15', '00066 a 00080', '5.175']
Contador inicial: 22
23 -- ['IPEM N° 270 GRAL M BELGRANO - DEAN FUNES 850', '11', '00081 a 00091', '3.795']
Contador inicial: 23
24 -- ['ESC SANTO TOMAS - CASEROS 745', '8', '00092 a 00099', '2.760']
Contador inicial: 24
25 -- ['ESC NORMAL ALEJANDRO CARBO - AV COLON 951', '13', '00100 a 00112', '4.474']
Contador inicial: 25
26 -- ['ESC MARIANO MORENO - SANTA ROSA ESQ SANTA FE 1.299', '13', '00113 a 00125', '4.472']
Contador inicial: 26
30 -- ['COL NACIONAL DEAN FUNES - PERU 10', '20', '00126 a 00145', '6.900']
Contador inicial: 30
31 -- ['IPET N°66 DR JOSE A BALSEIRO - HIPOLITO YRIGOYEN 258', '14', '00146 a 00159', '4.830']
Contador inicial: 31
32 -- ['ESC GDOR ALVAREZ - C ARENAL 699', '9', '00160 a 00168', '3.105']
Contador inicial: 32
33 -- ['FAC DE CIENCIAS ECONOMICAS - AV VALPARAISO CDAD UNIVERSITARIA', '18', '00169 a 00186', '6.194']
Contador inicial: 33
37 -- ['ESC ERNESTO BANCALARI - MONTERROSO B° ARTIGAS 4.597', '7', '00187 a 00193', '2.422']
Contador inicial: 37
38 -- ['ESC ALMAFUERTE - CHANETON B° SAN FERNANDO 390', '7', '00194 a 00200', '2.422']
Contador inicial: 38
39 -- ['ESC COM R ECHEGOYEN - J I DIAZ B° EJERCITO ARGENTINO 200', '8', '00201 a 00208', '2.768']
Contador inicial: 39
40 -- ['ESC SAN FRANCISCO DE ASIS - GUARDADO B°LAS FLORES 184', '30', '00209 a 00238', '10.351']
Contador inicial: 40
44 -- ['COL 20 DE JUNIO - BV DEL COMERCIO 835', '7', '00239 a 00245', '2.408']
Contador inicial: 44
45 -- ['INST EDUC NTRA SEÑORA - INCA MANCO - B°JARDIN ESPINOSA 3.450', '19', '00246 a 00264', '6.536']
Contador inicial: 45
46 -- ['ESC ING MASJOAN - P.L.DE CABRERA ESQ.TANTI B°V. REVOL', '9', '00265 a 00273', '3.096']
Contador inicial: 46
47 -- ['COL NICOLAS BERROTARAN - ELIAS YOFRE - B° JARDIN 1.095', '11', '00274 a 00284', '3.775']
Contador inicial: 47
51 -- ['ESC SAN JOSE DE CALASANZ - PIZARRO ESQ. NIVOLI', '6', '00285 a 00290', '1.996']
Contador inicial: 51
63 -- ['IPEN 310- PUERTO ARGENTINO - LUDUEÑA Y SARGENTO RIOS', '8', '00291 a 00298', '2.656']
Contador inicial: 63
67 -- ['COL VILLA EUCARISTICA - CNO A SAN CARLOS KM.5 1/2', '7', '00299 a 00305', '2.225']
Contador inicial: 67
71 -- ['ESC.SABIN - DDE.CMO.S.ANTONIO KM 7 1/2,1KM.AL O.', '8', '00306 a 00313', '2.596']
Contador inicial: 71
75 -- ['NSC.OSCAR RAUL MALVASIO - MANZANA 49 B° C.OBISPO ANGELELLI', '8', '00314 a 00321', '2.679']
Contador inicial: 75
79 -- ['ESC ESPAÑA - M BRAVO Y ENTRE RIOS', '17', '00322 a 00338', '5.780']
Contador inicial: 79
80 -- ['ESC GRECIA - PEDERNERA B°SAN VICENTE 952', '10', '00339 a 00348', '3.400']
Contador inicial: 80
81 -- ['ESC PANAMERICANA - SOTO   - B°ACOSTA 919', '9', '00349 a 00357', '3.058']
Contador inicial: 81
82 -- ['ESC ESTANISLAO DEL CAMPO - ESTADOS UNIDOS Y RIO 1° B°ALTAMIRA', '5', '00358 a 00362', '1.695']
Contador inicial: 82
86 -- ['ESC MUNICIPAL A GASTALDI - S JERONIMO/ALMAGRO COL LOLA 5.500', '6', '00363 a 00368', '1.998']
Contador inicial: 86
87 -- ['ELENA LOPEZ LALLANA - AGUSTIN GARZON 5.600', '10', '00369 a 00378', '3.324']
Contador inicial: 87
91 -- ['ESC   9 DE JULIO - JOSE A CABRERA°DEAN FUNES 4.717', '6', '00379 a 00384', '1.888']
Contador inicial: 91
95 -- ['ESC PROVINCIA DE LA RIOJA - JUNIN 3.480', '12', '00385 a 00396', '4.164']
Contador inicial: 95
96 -- ['ESC VICTOR MERCANTE - CAUCETE 4.008', '11', '00397 a 00407', '3.817']
Contador inicial: 96
97 -- ['ESC JUAN M DE PUEYRREDON - ANCASTI 4.555', '7', '00408 a 00414', '2.429']
Contador inicial: 97
98 -- ['INST SEC EMPALME GONZALEZ LACA - LAS ARRIAS 4.043', '5', '00415 a 00419', '1.735']
Contador inicial: 98
99 -- ['FRAY JUSTO STA MARÍA DE ORO - CALLAO 2.320', '12', '00420 a 00431', '4.163']
Contador inicial: 99
100 -- ['ELENA LOPEZ LALLANA - AGUSTÍN GARZON 5.636', '6', '00432 a 00437', '2.076']
Contador inicial: 100
104 -- ['ESC CANONIGO PIÑERO - CAMPO LA RIBERA', '6', '00438 a 00443', '2.046']
Contador inicial: 104
105 -- ['ESC MARTIN DE GÜEMES - OBPO CASTELLANOS B°MÜLLER 256', '9', '00444 a 00452', '3.069']
Contador inicial: 105
106 -- ['BAC TEC DR F ESCARDO - CAMPO LA RIBERA', '9', '00453 a 00461', '3.068']
Contador inicial: 106
107 -- ['IPEM 184-M.FRAGUEIRO - OB.CASTELLANO,S.VICENTE 955', '9', '00462 a 00470', '3.060']
Contador inicial: 107
121 -- ['ESC TTE GRAL P RICCHIERI - BENJAMIN VIEL 2.387', '12', '00471 a 00482', '4.072']
Contador inicial: 121
125 -- ['ESC M COOPERATIVISMO ARGENTINO - M BRAVO Y PJE.MATHEUB° RENACIMIENTO', '14', '00483 a 00496', '4.715']
Contador inicial: 125
129 -- ['ESC SANTA MARGARITA DE CORTONA - LOPEZ Y PLANES 2.936', '10', '00497 a 00506', '3.430']
Contador inicial: 129
130 -- ['ESC DGO F SARMIENTO - LOPEZ Y PLANES 2.253', '14', '00507 a 00520', '4.788']
Contador inicial: 130
131 -- ['ESC PTE RIVADAVIA - AGUSTIN GARZON 1.563', '12', '00521 a 00532', '4.104']
Contador inicial: 131
132 -- ['ESC MARIA IGNACIA NAVARRO DE L - CORRIENTES 2.006', '10', '00533 a 00542', '3.420']
Contador inicial: 132
136 -- ['ESC. MADRE MARIA DEL TRANSITO - MANZANA 7,', '6', '00543 a 00548', '1.944']
Contador inicial: 136
140 -- ['ESCUELA HEROES DE MALVINAS - CALLE PUBLICA S/N (CNO VILLA POSSE)', '8', '00549 a 00556', '2.728']
Contador inicial: 140
141 -- ['ESC.PTE. JUAN D.PERÓN - MANZANA 47', '7', '00557 a 00563', '2.383']
Contador inicial: 141
145 -- ['ESC TENIENTE GRAL ARAMBURU - GARIBALDI B°ALTO GRAL PAZ 710', '9', '00564 a 00572', '2.951']
Contador inicial: 145
146 -- ['COL   SAN RAMON NONATO - AVDA   PATRIA   B°ALTO GRAL PAZ 282', '7', '00573 a 00579', '2.289']
Contador inicial: 146
150 -- ['ESC MUNICIPAL DR   A SOBRAL - PUBLICA S/N°   B°SANGRE Y SOL', '1', '00580 a 00580', '294']
Contador inicial: 150
154 -- ['ESC VAN GELDEREN - CNO CHACRA DE LA MERCED KM 6 1/2', '1', '00581 a 00581', '216']
Contador inicial: 154
158 -- ['ESC RAMON J CARCANO - VIAMONTE 446', '11', '00582 a 00592', '3.806']
Contador inicial: 158
159 -- ['ESC NORMAL GARZON AGULLA - VIAMONTE 150', '14', '00593 a 00606', '4.844']
Contador inicial: 159
160 -- ['IPET N°10 COM MARTIN RIVADAVIA - 25 DE MAYO Y ROMA', '10', '00607 a 00616', '3.457']
Contador inicial: 160
164 -- ['ESC GABRIELA MISTRAL - LEONOR DE TEJEDA 1.353', '10', '00617 a 00626', '3.390']
Contador inicial: 164
165 -- ['ESC BRIGADIER C SAAVEDRA - ARENALES Y LA PLATA', '12', '00627 a 00638', '4.059']
Contador inicial: 165
179 -- ['ESC TRANSITO CACERES DE ALLEND - CNO CHACRA DE LA MERCED KM 9 Y 1/2', '7', '00639 a 00645', '2.291']
Contador inicial: 179
183 -- ['ESC R GÜIRALDES - 24 DE SETIEMBRE 2.400', '12', '00646 a 00657', '4.092']
Contador inicial: 183
184 -- ['ESC GDOR AMADEO SABATTINI - GERMANIA 2.500', '12', '00658 a 00669', '4.081']
Contador inicial: 184
188 -- ['ESC JORGE NEWBERY (CIRC 7F) - MATIENZO 5.895', '1', '00670 a 00670', '112']
Contador inicial: 188
192 -- ['IPEM N° 22 JUAN FILLOY - CALLE DE LA CUECA', '6', '00671 a 00676', '2.040']
Contador inicial: 192
193 -- ['ESC   UNESCO - JUAN B JUSTO/AV N SRA D LOS MILAGROS', '14', '00677 a 00690', '4.747']
Contador inicial: 193
197 -- ['ESC MANUEL LUCERO - MANUEL LUCERO 560', '19', '00691 a 00709', '6.555']
Contador inicial: 197
198 -- ['ESC PCIA DE ENTRE RIOS - TRAFALGAR 845', '11', '00710 a 00720', '3.795']
Contador inicial: 198
199 -- ['INST CORAZON DE MARIA - A DEL VISO 445', '14', '00721 a 00734', '4.830']
Contador inicial: 199
200 -- ['INST NUESTRA MADRE DE LA MERCE - M FRAGUEIRO 2.400', '13', '00735 a 00747', '4.476']
Contador inicial: 200
201 -- ['INST MANUEL LUCERO - LAVALLEJA 2.257', '9', '00748 a 00756', '3.096']
Contador inicial: 201
205 -- ['ESC J NEWBERY - MATIENZO 5.895', '1', '00757 a 00757', '8']
Contador inicial: 205
209 -- ['ESC PTE SARMIENTO - R SAENZ PEÑA 1.212', '11', '00758 a 00768', '3.718']
Contador inicial: 209
210 -- ['ESC PCIA DE FORMOSA - RODRIGUEZ PEÑA 1.548', '8', '00769 a 00776', '2.703']
Contador inicial: 210
211 -- ['ESC. GARCIA FAURE - JERONIMO LUIS DE CABRERA 834', '10', '00777 a 00786', '3.370']
Contador inicial: 211
215 -- ['ESC HONORATO LACONI - T DE IROBI', '15', '00787 a 00801', '5.205']
Contador inicial: 215
216 -- ['ESC PETER PAN - P DE GUZMAN', 'B°M DE SOBREMONTE 131', '15', '00802 a 00816', '5.198']
Contador inicial: 216
217 -- ['J DE INF B.RIVADAVIA - NUFLO DE AGUILAR 541', '3', '00817 a 00819', '1.038']
Contador inicial: 217
218 -- ['JOSE LUIS SERCIC - PEREZ CORREA', 'M DE SOBREMONTE 1.500', '8', '00820 a 00827', '2.768']
Contador inicial: 218
219 -- ['IPEM 338 - FRANCISCO SUAREZ 3.760', '7', '00828 a 00834', '2.422']
Contador inicial: 219
223 -- ['ESC JORGE NEWBERY - BENJAMIN MATIENZO 5.895', '10', '00835 a 00844', '3.440']
Contador inicial: 223
234 -- ['ESC NACIONES UNIDAS - CTDA', '8 S/N', '9', '00845 a 00853', '3.096']
Contador inicial: 234
235 -- ['IPEM 121 PAEZ MOLINA - ORIGONE ESQ CAROLA LORENZINI', '5', '00854 a 00858', '1.715']
Contador inicial: 235
239 -- ['ESC GOBERNADOR MANUEL LOPEZ - URQUIZA 4.800', '7', '00859 a 00865', '2.373']
Contador inicial: 239
240 -- ['ESC ARTURO CAPDEVILA - AVELLANEDA B°MFRAGUEIRO 4.100', '12', '00866 a 00877', '4.068']
Contador inicial: 240
241 -- ['ESC FRANCISCO VIDAL - FRAGUEIRO', '(MANZANA "C") 4.200', '12', '00878 a 00889', '4.062']
Contador inicial: 241
242 -- ['IPEM 199 "JUAN EMILIO REMONDA" - SOSA REVELLO Y 15 DE SEPTIEMBRE 590', '7', '00890 a 00896', '2.366']
Contador inicial: 242
246 -- ['ESC   RABINDRANAT TAGORE - OCARINA', '- B° V CLAUDINA 1.613', '3', '00897 a 00899', '784']
Contador inicial: 246
250 -- ['ESC EMILIO E SANCHEZ - ANTONIO MACHONI 1.700', '12', '00900 a 00911', '4.073']
Contador inicial: 250
254 -- ['ESC FRAY J A DE SAN ALBERTO - ESQUIU', 'B°PUEYRREDON 1.340', '7', '00912 a 00918', '2.408']
Contador inicial: 254
255 -- ['INST OBISPO CAIXAL - ANA M JANER B°PUEYRREDON 1.250', '8', '00919 a 00926', '2.752']
Contador inicial: 255
256 -- ['ESC DEAN FUNES - ANA M JANER B°PUEYRREDON 1.551', '10', '00927 a 00936', '3.440']
Contador inicial: 256
257 -- ['INST SAGRADO CORAZON - ROMA', 'B°PUEYRREDON 1.153', '10', '00937 a 00946', '3.438']
Contador inicial: 257
258 -- ['ESC ROBLES - PADRE LUIS MONTI', 'B°PUEYRREDON 1.850', '13', '00947 a 00959', '4.459']
Contador inicial: 258
259 -- ['INST SAGRADA FAMILIA - BUCHARDO 1.729', '10', '00960 a 00969', '3.430']
Contador inicial: 259
263 -- ['ESC TRINIDAD MORENO - E SAN MARTIN 1.251', '12', '00970 a 00981', '4.068']
Contador inicial: 263
264 -- ['ESC ALMIRANTE BROWN - SAN MARTIN S/N°', '13', '00982 a 00994', '4.400']
Contador inicial: 264
268 -- ['ESC PROVINCIA DE CORRIENTES - DOMINGO ZIPOLI 1.358', '8', '00995 a 01002', '2.632']
Contador inicial: 268
269 -- ['INST ESCUTI - NAZARET   - 3.399', '10', '01003 a 01012', '3.284']
Contador inicial: 269
273 -- ['ESC MAHATMA GANDHI - TALAVERA DE MADRID 3.261', '7', '01013 a 01019', '2.331']
Contador inicial: 273
274 -- ['COL PQUIAL C NAMUNCURA - DIAGUITAS 3.314', '8', '01020 a 01027', '2.656']
Contador inicial: 274
278 -- ['ESC   RICARDO ROJAS - J.LOPEZ', 'B°ALTOS DE V CABRERA 2.050', '8', '01028 a 01035', '2.672']
Contador inicial: 278
279 -- ['ESC CONGRESO DE TUCUMAN - MALVINO B°LAS MARGARITAS 2.772', '6', '01036 a 01041', '2.004']
Contador inicial: 279
290 -- ['ESC MIGUEL RODRIGUEZ DE LA TOR - LA GRANJA B°ALTO VERDE 3.199', '10', '01042 a 01051', '3.333']
Contador inicial: 290
294 -- ['ESC DE COMERCIO J J PASO - PLATON', 'B°LOS PARAISOS 3.030', '10', '01052 a 01061', '3.440']
Contador inicial: 294
295 -- ['COLEGIO FERMIN LAFITTE - FCO VALLE 2.443', '10', '01062 a 01071', '3.440']
Contador inicial: 295
296 -- ['ESC JUVENILIA - ZARATE   - 2.083', '7', '01072 a 01078', '2.408']
Contador inicial: 296
297 -- ['ESC PCIA', 'DE MISIONES - FIRPO 2.254', '14', '01079 a 01092', '4.810']
Contador inicial: 297
301 -- ['COL EL SALVADOR - RAUL CASARIEGO B°P LUGONES 4.479', '8', '01093 a 01100', '2.744']
Contador inicial: 301
302 -- ['ESC LEOPOLDO LUGONES - LESPADA Y GALVEZ', '10', '01101 a 01110', '3.424']
Contador inicial: 302
303 -- ['IPEM 198 MARTIN FERREYRA - CAMAÑO BAZAN E/CARLES Y A.GRIMAU', '9', '01111 a 01119', '3.078']
Contador inicial: 303
307 -- ['ESC PTE HIPOLITO YRIGOYEN - CASTRO BARROS 802', '15', '01120 a 01134', '5.033']
Contador inicial: 307
311 -- ['ESC ANTONIO DEL VISO - SAAVEDRA 619', '13', '01135 a 01147', '4.420']
Contador inicial: 311
312 -- ['INST INMACULADA CONCEPCION - CASTRO BARROS 1.316', '17', '01148 a 01164', '5.777']
Contador inicial: 312
313 -- ['ESC J DE SAN MARTIN - CERRITO Y GALAN', '7', '01165 a 01171', '2.373']
Contador inicial: 313
314 -- ['COL NTRA SEÑORA DE LA MERCED - ZELAYA 140', '8', '01172 a 01179', '2.712']
Contador inicial: 314
318 -- ['INSTITUTO PEÑA - CIUDAD DE TAMPA 2.954', '11', '01180 a 01190', '3.795']
Contador inicial: 318
319 -- ['ESC PRESIDENTE KENNEDY - JULIAN PAZ 1.851', '6', '01191 a 01196', '2.064']
Contador inicial: 319
323 -- ['ESC ROQUE SAENZ PEÑA - AV VELEZ SARSFIELD 1.000', '14', '01197 a 01210', '4.814']
Contador inicial: 323
324 -- ['INST EDUCACION CORDOBA - FERREYRA Y FRIULI B°COL DE V SARSF', '19', '01211 a 01229', '6.517']
Contador inicial: 324
325 -- ['E.N.E.T. N°1 DR A SABATTINI - AV VELEZ SARSFIELD 1.490', '10', '01230 a 01239', '3.430']
Contador inicial: 325
326 -- ['ESC MANUEL BELGRANO - SUECIA B° PQUE VELEZ SARSFIELD 2.832', '10', '01240 a 01249', '3.430']
Contador inicial: 326
330 -- ['ESC MUN YAMAHIBIA ARABE LIBIA - COLORADO/GAIMAN/MASCACHIN', '9', '01250 a 01258', '3.033']
Contador inicial: 330
331 -- ['IPEM 311 - USUAHIA 2.150', '6', '01259 a 01264', '2.016']
Contador inicial: 331
335 -- ['ESC PCIA DE CATAMARCA - AV VELEZ SARSFIELD 3.200', '17', '01265 a 01281', '5.761']
Contador inicial: 335
346 -- ['ESC REPUBLICA DE SIRIA - TRAFUL', 'B°PQUE ATLANTICA 908', '6', '01282 a 01287', '2.028']
Contador inicial: 346
347 -- ['ESC GDOR J B BUSTOS - CACHEUTA Y BRANDAN-ALTO V.SARSFIELD', '11', '01288 a 01298', '3.718']
Contador inicial: 347
348 -- ['J DE INF REPUBLICA DE SIRIA - VIRGILIO MOYANO 830', '2', '01299 a 01300', '676']
Contador inicial: 348
352 -- ['ESC ALEJANDRO CARBO - ICHO CRUZ S/N°', '16', '01301 a 01316', '5.376']
Contador inicial: 352
353 -- ['ESC MUNIC AZOR GRIMAUT - SOBREMONTE Y RIO III', '5', '01317 a 01321', '1.679']
Contador inicial: 353
357 -- ['ESC MUNIC REPUBLICA DE ITALIA - REALICO Y CURAZAO', '7', '01322 a 01328', '2.226']
Contador inicial: 357
358 -- ['IPEM 183"PEDRO B.PALACIOS" - REALICO', '- 2.407', '4', '01329 a 01332', '1.270']
Contador inicial: 358
362 -- ['ESC CADETES FUERZA AEREA - LEOPOLDO CASAVEGA 2.320', '11', '01333 a 01343', '3.740']
Contador inicial: 362
363 -- ['ESC PADRE BURON - AVIADOR MIRA 2.658', '8', '01344 a 01351', '2.718']
Contador inicial: 363
364 -- ['J DE INF CADETES FUERZA AEREA - LEOPOLDO CASAVEGA 2.320', '2', '01352 a 01353', '678']
Contador inicial: 364
365 -- ['ESC   ALAS ARGENTINA - BONN 4.627', '11', '01354 a 01364', '3.729']
Contador inicial: 365
366 -- ['ESC MUNIC CESAR E ROMERO - PUBLICA S/N', '6', '01365 a 01370', '2.034']
Contador inicial: 366
370 -- ['ESC AERONAUTICA ARGENTINA - ESMERALDA/CAP GRELLA', '10', '01371 a 01380', '3.470']
Contador inicial: 370
371 -- ['COL NUESTRA SEÑORA DE FATIMA - VARELA ORTIZ 2.600', '13', '01381 a 01393', '4.511']
Contador inicial: 371
372 -- ['ESC REPUBLICA ARGENTINA - SAN CAYETANO Y BRAILE', '7', '01394 a 01400', '2.429']
Contador inicial: 372
373 -- ['ESC MIGUEL A ZABALA ORTIZ - DIAZ DE LA FUENTE 3.101', '7', '01401 a 01407', '2.423']
Contador inicial: 373
377 -- ['E.N.E.T. N° 4 COPERNICO - MARIANO MORENO 551', '26', '01408 a 01433', '9.011']
Contador inicial: 377
378 -- ['EE UU DE NORTEAMERICA - LA PAMPA 550', '9', '01434 a 01442', '3.114']
Contador inicial: 378
379 -- ['COL   NUESTRA SEÑORA DE NIEVA - AYACUCHO 442', '18', '01443 a 01460', '6.228']
Contador inicial: 379
380 -- ['ESC ADOLFO SALDIAS - BOLIVAR 896', '8', '01461 a 01468', '2.768']
Contador inicial: 380
384 -- ['ESC GDOR EMILIO OLMOS - AV FUERZA AEREA', 'B°PARQUE CAPITAL', '10', '01469 a 01478', '3.380']
Contador inicial: 384
385 -- ['ESC R ESCALADA DE SAN MARTIN - ESPORA 2.283', '14', '01479 a 01492', '4.732']
Contador inicial: 385
386 -- ['ESC MUNIC DR A DEL CASTILLO - UNO ESQ DOCE', '7', '01493 a 01499', '2.366']
Contador inicial: 386
387 -- ['IPEM 154 MARTIN M DE GUEMES - O NAVARRO 2.751', '6', '01500 a 01505', '2.024']
Contador inicial: 387
400 -- ['PRIMARIA ELPIDIO TORRES - CALLE PUBLICA S/N', '12', '01506 a 01517', '4.046']
Contador inicial: 400
401 -- ['INST. SAN JOSE ARTESANO - CORONDA ESQ HUILICHES', '6', '01518 a 01523', '2.022']
Contador inicial: 401
402 -- ['IPEM 357 (SEC ELPIDIO TORRES) - CALLE PUBLICA S/N', '13', '01524 a 01536', '4.381']
Contador inicial: 402
406 -- ['ESC BANDERA ARGENTINA - CASADO', 'STA ISABEL 1RA SECCION 634', '11', '01537 a 01547', '3.754']
Contador inicial: 406
407 -- ['ESCUELA DON ORIONE - J.B.COTTOLENGO 1.955', '12', '01548 a 01559', '4.092']
Contador inicial: 407
408 -- ['ESC MUNIC FERNANDEZ ORDOÑEZ - OLAVARRIA S/N° STA ISABEL 2DA SECC', '7', '01560 a 01566', '2.387']
Contador inicial: 408
409 -- ['ESC.OSVALDO JORGE LEON - COLORADO ESQ LUAYABA', '7', '01567 a 01573', '2.387']
Contador inicial: 409
413 -- ['ESC BENITO SORIA - BARBADOS Y HAITI', '11', '01574 a 01584', '3.817']
Contador inicial: 413
414 -- ['COLEGIO PRIVADO SAN ISIDRO - ARMADA ARGENTINA 3.648', '5', '01585 a 01589', '1.734']
Contador inicial: 414
418 -- ['IPEM 313 (ANEX0) - DEFENSA Y CACHEUTA,V.EL LIBERTADOR', '6', '01590 a 01595', '2.082']
Contador inicial: 418
419 -- ['ESC PROV DE SGO DEL ESTERO - CALLE 49S/N VILLA EL LIBERTADOR', '8', '01596 a 01603', '2.776']
Contador inicial: 419
420 -- ['ESC MARTA JUANA GONZALEZ - DEFENSA Y CACHEUTA B°V.EL LIBERTADOR 1.091', '10', '01604 a 01613', '3.470']
Contador inicial: 420
421 -- ['ESC MUNIC ALICIA MOREAU DE JUS - PILCOMAYO S/N°V EL LIBERTADOR', '8', '01614 a 01621', '2.776']
Contador inicial: 421
422 -- ['ESC PTE DR ARTURO U ILLIA - TOTORAL Y ARICA B°SANTA ROSA', '11', '01622 a 01632', '3.817']
Contador inicial: 422
423 -- ['COL SAN JOSE OBRERO - ARANI Y PJE. 17 V EL LIBERTADOR', '6', '01633 a 01638', '2.082']
Contador inicial: 423
424 -- ['J DE INF DR ARTURO U ILLIA - ARICA Y TOTORAL', '4', '01639 a 01642', '1.388']
Contador inicial: 424
425 -- ['ESC VICENTE FORESTIERI - ANIZACATE/CALLE 49 V. EL LIBERTADOR', '9', '01643 a 01651', '3.123']
Contador inicial: 425
426 -- ['IPEM 123BLANCA ECHEMENDI - IBARRA ESQUINA COSQUIN', '10', '01652 a 01661', '3.466']
Contador inicial: 426
427 -- ['ESC PATRICIAS MENDOCINAS - IBARRA ESQ FORESITERI', '5', '01662 a 01666', '1.730']
Contador inicial: 427
431 -- ['ESC PRIMARIA GRACIELA DEL RIO - CALE S/N', '6', '01667 a 01672', '1.868']
Contador inicial: 431
435 -- ['ESC ISABEL LA CATOLICA - SUBOF OTANO S/N°', '14', '01673 a 01686', '4.728']
Contador inicial: 435
439 -- ['ESC PQUIAL SAN JOSE - VELEZ', 'B° 252', '12', '01687 a 01698', '4.164']
Contador inicial: 439
440 -- ['ESC SUP DE COMERCIO H VIEYTES - CASEROS Y VIEYTES', '10', '01699 a 01708', '3.470']
Contador inicial: 440
441 -- ['ESC BLAS PARERA - MONS DE ANDREA 1.044', '7', '01709 a 01715', '2.427']
Contador inicial: 441
442 -- ['ESC SAN JOSE - CASEROS 3.055', '11', '01716 a 01726', '3.806']
Contador inicial: 442
443 -- ['ESC SAN LUIS GONZAGA - SANTA ROSA 2.037', '9', '01727 a 01735', '3.114']
Contador inicial: 443
454 -- ['ESC JOSE MARIA PAZ - AV COLON 2.772', '15', '01736 a 01750', '5.190']
Contador inicial: 454
455 -- ['ESC MOYANO COUDERT - DUARTE QUIROS 3.950', '4', '01751 a 01754', '1.384']
Contador inicial: 455

In [28]:
print(discontinuidades)
print("Establecimientos:", len(escuelas))
print("Discontinuidades:", len(discontinuidades))
print("Última mesa:", last_mesa)
for d in discontinuidades:
    print(d)

[{'linea': 2320, 'esperada': 6000, 'encontrada': 6001, 'establecimiento': 'ESC NICOLAS AVELLANEDA - VICENTE LOPEZ 538'}, {'linea': 2391, 'esperada': 6339, 'encontrada': 6000, 'establecimiento': 'ESCUELA N°359 - WASHINGTON'}, {'linea': 3325, 'esperada': 7780, 'encontrada': 7788, 'establecimiento': 'ESCUELA JOSE MARIA PAZ - LOS ANDES(B°CAMARA) 80'}, {'linea': 3326, 'esperada': 7797, 'encontrada': 7780, 'establecimiento': 'ESCUELA MANUEL SOLARES - ESPAÑA 26'}, {'linea': 3327, 'esperada': 7788, 'encontrada': 7797, 'establecimiento': 'ESC SANTIAGO DE LINIERS - B°LINIERS'}]
Establecimientos: 1211
Discontinuidades: 5
Última mesa: 8649
{'linea': 2320, 'esperada': 6000, 'encontrada': 6001, 'establecimiento': 'ESC NICOLAS AVELLANEDA - VICENTE LOPEZ 538'}
{'linea': 2391, 'esperada': 6339, 'encontrada': 6000, 'establecimiento': 'ESCUELA N°359 - WASHINGTON'}
{'linea': 3325, 'esperada': 7780, 'encontrada': 7788, 'establecimiento': 'ESCUELA JOSE MARIA PAZ - LOS ANDES(B°CAMARA) 80'}
{'linea': 3326, 'esperada': 7797, 'encontrada': 7780, 'establecimiento': 'ESCUELA MANUEL SOLARES - ESPAÑA 26'}
{'linea': 3327, 'esperada': 7788, 'encontrada': 7797, 'establecimiento': 'ESC SANTIAGO DE LINIERS - B°LINIERS'}

In [25]:
print("Electores:", sum(e["electores"] for e in escuelas))

Electores: 2884358

# Diagnostico de filas problematicas por su nombre y domicilio
para despues limpar a mano

In [29]:
# ============================================================
# DIAGNÓSTICO INDEPENDIENTE DE FILAS PROBLEMÁTICAS
# No modifica las variables del parser definitivo
# ============================================================

modo_diag = ""
linea_diag = 0
ultima_mesa_diag = 0

filas_correctas_diag = 0
filas_problematicas = []
discontinuidades_diag = []

for linea in lines:
    linea_diag += 1

    # Ignorar encabezados y elementos que no son escuelas
    if "Página" in linea:
        continue

    if linea.strip() == "DISTRITO CORDOBA":
        continue

    if "ELECCIONES 20" in linea:
        continue

    if "Informe de Establecimientos" in linea:
        continue

    if linea.startswith("Sección "):
        modo_diag = ""
        continue

    if linea.startswith(" Circuito"):
        modo_diag = "escuelas"
        continue

    if linea == "":
        continue

    if linea.startswith("Resúmen del Circuito"):
        modo_diag = ""
        continue

    # Solo analizar líneas que deberían contener escuelas
    if modo_diag == "escuelas":
        partes = linea.split("    ")
        datos = [x.strip() for x in partes if x.strip() != ""]

        try:
            # Se prueba exactamente la estructura del parser original
            escuela = datos[0]
            cant_mesas = int(datos[1])

            rango_mesas = datos[2].split(" a ")
            mesa_desde = int(rango_mesas[0])
            mesa_hasta = int(rango_mesas[1])

            cant_electores = int(datos[3].replace(".", ""))

            # Registrar discontinuidades, pero sin detener el diagnóstico
            if mesa_desde != ultima_mesa_diag + 1:
                discontinuidades_diag.append({
                    "linea": linea_diag,
                    "esperada": ultima_mesa_diag + 1,
                    "encontrada": mesa_desde,
                    "contenido": linea,
                })

            ultima_mesa_diag = mesa_hasta
            filas_correctas_diag += 1

        except Exception as error:
            filas_problematicas.append({
                "linea": linea_diag,
                "contenido": linea,
                "datos": datos,
                "error": str(error),
            })

            print(f"Fila problemática en línea {linea_diag}")
            print(f"Datos obtenidos: {datos}")
            print(f"Error: {error}")
            print("-" * 80)

            # Intentar recuperar solamente el rango de mesas para que
            # el diagnóstico pueda continuar con la numeración correcta
            for fragmento in datos:
                if " a " in fragmento:
                    try:
                        rango_auxiliar = fragmento.split(" a ")
                        mesa_desde_aux = int(rango_auxiliar[0])
                        mesa_hasta_aux = int(rango_auxiliar[1])

                        if mesa_desde_aux != ultima_mesa_diag + 1:
                            discontinuidades_diag.append({
                                "linea": linea_diag,
                                "esperada": ultima_mesa_diag + 1,
                                "encontrada": mesa_desde_aux,
                                "contenido": linea,
                            })

                        ultima_mesa_diag = mesa_hasta_aux
                        break

                    except ValueError:
                        pass

            continue

Fila problemática en línea 216
Datos obtenidos: ['ESC PETER PAN - P DE GUZMAN', 'B°M DE SOBREMONTE 131', '15', '00802 a 00816', '5.198']
Error: invalid literal for int() with base 10: 'B°M DE SOBREMONTE 131'
--------------------------------------------------------------------------------
Fila problemática en línea 218
Datos obtenidos: ['JOSE LUIS SERCIC - PEREZ CORREA', 'M DE SOBREMONTE 1.500', '8', '00820 a 00827', '2.768']
Error: invalid literal for int() with base 10: 'M DE SOBREMONTE 1.500'
--------------------------------------------------------------------------------
Fila problemática en línea 234
Datos obtenidos: ['ESC NACIONES UNIDAS - CTDA', '8 S/N', '9', '00845 a 00853', '3.096']
Error: invalid literal for int() with base 10: '8 S/N'
--------------------------------------------------------------------------------
Fila problemática en línea 241
Datos obtenidos: ['ESC FRANCISCO VIDAL - FRAGUEIRO', '(MANZANA "C") 4.200', '12', '00878 a 00889', '4.062']
Error: invalid literal for int() with base 10: '(MANZANA "C") 4.200'
--------------------------------------------------------------------------------
Fila problemática en línea 246
Datos obtenidos: ['ESC   RABINDRANAT TAGORE - OCARINA', '- B° V CLAUDINA 1.613', '3', '00897 a 00899', '784']
Error: invalid literal for int() with base 10: '- B° V CLAUDINA 1.613'
--------------------------------------------------------------------------------
Fila problemática en línea 254
Datos obtenidos: ['ESC FRAY J A DE SAN ALBERTO - ESQUIU', 'B°PUEYRREDON 1.340', '7', '00912 a 00918', '2.408']
Error: invalid literal for int() with base 10: 'B°PUEYRREDON 1.340'
--------------------------------------------------------------------------------
Fila problemática en línea 257
Datos obtenidos: ['INST SAGRADO CORAZON - ROMA', 'B°PUEYRREDON 1.153', '10', '00937 a 00946', '3.438']
Error: invalid literal for int() with base 10: 'B°PUEYRREDON 1.153'
--------------------------------------------------------------------------------
Fila problemática en línea 258
Datos obtenidos: ['ESC ROBLES - PADRE LUIS MONTI', 'B°PUEYRREDON 1.850', '13', '00947 a 00959', '4.459']
Error: invalid literal for int() with base 10: 'B°PUEYRREDON 1.850'
--------------------------------------------------------------------------------
Fila problemática en línea 278
Datos obtenidos: ['ESC   RICARDO ROJAS - J.LOPEZ', 'B°ALTOS DE V CABRERA 2.050', '8', '01028 a 01035', '2.672']
Error: invalid literal for int() with base 10: 'B°ALTOS DE V CABRERA 2.050'
--------------------------------------------------------------------------------
Fila problemática en línea 294
Datos obtenidos: ['ESC DE COMERCIO J J PASO - PLATON', 'B°LOS PARAISOS 3.030', '10', '01052 a 01061', '3.440']
Error: invalid literal for int() with base 10: 'B°LOS PARAISOS 3.030'
--------------------------------------------------------------------------------
Fila problemática en línea 297
Datos obtenidos: ['ESC PCIA', 'DE MISIONES - FIRPO 2.254', '14', '01079 a 01092', '4.810']
Error: invalid literal for int() with base 10: 'DE MISIONES - FIRPO 2.254'
--------------------------------------------------------------------------------
Fila problemática en línea 346
Datos obtenidos: ['ESC REPUBLICA DE SIRIA - TRAFUL', 'B°PQUE ATLANTICA 908', '6', '01282 a 01287', '2.028']
Error: invalid literal for int() with base 10: 'B°PQUE ATLANTICA 908'
--------------------------------------------------------------------------------
Fila problemática en línea 358
Datos obtenidos: ['IPEM 183"PEDRO B.PALACIOS" - REALICO', '- 2.407', '4', '01329 a 01332', '1.270']
Error: invalid literal for int() with base 10: '- 2.407'
--------------------------------------------------------------------------------
Fila problemática en línea 384
Datos obtenidos: ['ESC GDOR EMILIO OLMOS - AV FUERZA AEREA', 'B°PARQUE CAPITAL', '10', '01469 a 01478', '3.380']
Error: invalid literal for int() with base 10: 'B°PARQUE CAPITAL'
--------------------------------------------------------------------------------
Fila problemática en línea 406
Datos obtenidos: ['ESC BANDERA ARGENTINA - CASADO', 'STA ISABEL 1RA SECCION 634', '11', '01537 a 01547', '3.754']
Error: invalid literal for int() with base 10: 'STA ISABEL 1RA SECCION 634'
--------------------------------------------------------------------------------
Fila problemática en línea 439
Datos obtenidos: ['ESC PQUIAL SAN JOSE - VELEZ', 'B° 252', '12', '01687 a 01698', '4.164']
Error: invalid literal for int() with base 10: 'B° 252'
--------------------------------------------------------------------------------
Fila problemática en línea 511
Datos obtenidos: ['ESC REPUBLICA DE VENEZUELA - BOYERO', '- 517', '10', '01977 a 01986', '3.400']
Error: invalid literal for int() with base 10: '- 517'
--------------------------------------------------------------------------------
Fila problemática en línea 525
Datos obtenidos: ['ESC LUTERANO CONCORDIA - SANTA ANA', 'B°ALTO ALBERDI 2.011', '16', '02051 a 02066', '5.535']
Error: invalid literal for int() with base 10: 'B°ALTO ALBERDI 2.011'
--------------------------------------------------------------------------------
Fila problemática en línea 531
Datos obtenidos: ['ESC EJERCITO ARGENTINO - LA RIOJA', '- B° VILLA SIBURU 3.453', '8', '02085 a 02092', '2.752']
Error: invalid literal for int() with base 10: '- B° VILLA SIBURU 3.453'
--------------------------------------------------------------------------------
Fila problemática en línea 549
Datos obtenidos: ['ESC CONSTANCIO C VIGIL - J.LLERENA', '- 5.561', '8', '02152 a 02159', '2.718']
Error: invalid literal for int() with base 10: '- 5.561'
--------------------------------------------------------------------------------
Fila problemática en línea 583
Datos obtenidos: ['ESC MONSEÑOR M DE ANDREA - 17 DE JULIO', 'B°FVRO MITRE 380', '10', '02265 a 02274', '3.453']
Error: invalid literal for int() with base 10: 'B°FVRO MITRE 380'
--------------------------------------------------------------------------------
Fila problemática en línea 621
Datos obtenidos: ['ESC PRIMARIA CARLOS M DE ALVEA - VUCETICH', 'B°ITUZAINGO 6.410', '7', '02417 a 02423', '2.429']
Error: invalid literal for int() with base 10: 'B°ITUZAINGO 6.410'
--------------------------------------------------------------------------------
Fila problemática en línea 641
Datos obtenidos: ['ESC ARISTOBULO DEL VALLE - M DE JAUREGUI', 'B°L N ALEM 1.657', '10', '02502 a 02511', '3.430']
Error: invalid literal for int() with base 10: 'B°L N ALEM 1.657'
--------------------------------------------------------------------------------
Fila problemática en línea 642
Datos obtenidos: ['ESC ASOCIACION DE MAYO - COLOMPREA', 'B° ALEM 1.500', '5', '02512 a 02516', '1.715']
Error: invalid literal for int() with base 10: 'B° ALEM 1.500'
--------------------------------------------------------------------------------
Fila problemática en línea 711
Datos obtenidos: ['ESC A CAPDEVILA/ DR. B HOUSEY - A CAPDEVILA', 'Y BILIBISACATE 709', '11', '02768 a 02778', '3.817']
Error: invalid literal for int() with base 10: 'Y BILIBISACATE 709'
--------------------------------------------------------------------------------
Fila problemática en línea 712
Datos obtenidos: ['ESC CURA BROCHERO - JAMAICA', 'B°RESID AMERICA 967', '12', '02779 a 02790', '4.164']
Error: invalid literal for int() with base 10: 'B°RESID AMERICA 967'
--------------------------------------------------------------------------------
Fila problemática en línea 715
Datos obtenidos: ['ESC JUSTO PAEZ MOLINA - J MONTAÑO', 'B° VILLA AZALAIZ 1.350', '14', '02811 a 02824', '4.858']
Error: invalid literal for int() with base 10: 'B° VILLA AZALAIZ 1.350'
--------------------------------------------------------------------------------
Fila problemática en línea 716
Datos obtenidos: ['ESC VICENTE F LOPEZ - TISSERA', 'B° L N ALEM 1.551', '15', '02825 a 02839', '5.205']
Error: invalid literal for int() with base 10: 'B° L N ALEM 1.551'
--------------------------------------------------------------------------------
Fila problemática en línea 727
Datos obtenidos: ['ESC MUNIC J A PAREDES - FCO DEL PRADO', 'V AZALAIS 3.900', '8', '02840 a 02847', '2.776']
Error: invalid literal for int() with base 10: 'V AZALAIS 3.900'
--------------------------------------------------------------------------------
Fila problemática en línea 787
Datos obtenidos: ['ESC JUAN ZORRILA DE SAN MARTIN - JOSE E BUSTOS', 'C DE LAS ROSAS 1.875', '11', '03016 a 03026', '3.624']
Error: invalid literal for int() with base 10: 'C DE LAS ROSAS 1.875'
--------------------------------------------------------------------------------
Fila problemática en línea 818
Datos obtenidos: ['ESC   REPUBLICA DE PANAMA - TRECE BIS', 'COL   DEL CERRO', '7', '03125 a 03131', '2.352']
Error: invalid literal for int() with base 10: 'COL   DEL CERRO'
--------------------------------------------------------------------------------
Fila problemática en línea 860
Datos obtenidos: ['ESC MUNIC DR JORGE ORGAZ - LAGUNA LARGA/R LUNA', 'V R INDARTE', '7', '03240 a 03246', '2.257']
Error: invalid literal for int() with base 10: 'V R INDARTE'
--------------------------------------------------------------------------------
Fila problemática en línea 1113
Datos obtenidos: ['ESC CIUDAD DE MALVINAS ARGENT. - AV SAN MARTIN', '2°SECC. 600', '12', '03742 a 03753', '4.152']
Error: invalid literal for int() with base 10: '2°SECC. 600'
--------------------------------------------------------------------------------
Fila problemática en línea 1213
Datos obtenidos: ['4.077 asociada a 4.076']
Error: list index out of range
--------------------------------------------------------------------------------
Fila problemática en línea 1493
Datos obtenidos: ['4.392 asociada a 4.390']
Error: list index out of range
--------------------------------------------------------------------------------
Fila problemática en línea 1494
Datos obtenidos: ['4.393 asociada a 4.391']
Error: list index out of range
--------------------------------------------------------------------------------
Fila problemática en línea 1579
Datos obtenidos: ['ESC.M.J.G.DE BELGRANO - JERONIMO L DE CABRERA', 'L ALGARROBOS 451', '10', '04678 a 04687', '3.450']
Error: invalid literal for int() with base 10: 'L ALGARROBOS 451'
--------------------------------------------------------------------------------
Fila problemática en línea 1819
Datos obtenidos: ['ESC MARIANO MORENO - SAN JUAN', 'SUR 1.090', '8', '05123 a 05130', '2.742']
Error: invalid literal for int() with base 10: 'SUR 1.090'
--------------------------------------------------------------------------------
Fila problemática en línea 1820
Datos obtenidos: ['ESCUELA BARTOLOME MITRE - HIPOLITO YRIGOYEN', 'NOROESTE 1.409', '7', '05131 a 05137', '2.394']
Error: invalid literal for int() with base 10: 'NOROESTE 1.409'
--------------------------------------------------------------------------------
Fila problemática en línea 2068
Datos obtenidos: ['INST ALFONSINA STORNI(EX IESS) - SOLIS', 'B° VILLA DOMINGUEZ 283', '21', '05477 a 05497', '7.266']
Error: invalid literal for int() with base 10: 'B° VILLA DOMINGUEZ 283'
--------------------------------------------------------------------------------
Fila problemática en línea 2164
Datos obtenidos: ['INSTITUTO ADELIA MARIA - AV SAN MARTIN', 'CENTRO 1.050', '11', '05713 a 05723', '3.740']
Error: invalid literal for int() with base 10: 'CENTRO 1.050'
--------------------------------------------------------------------------------
Fila problemática en línea 2165
Datos obtenidos: ['ESC GENERAL SAN MARTIN - SARMIENTO', 'CENTRO 98', '8', '05724 a 05731', '2.713']
Error: invalid literal for int() with base 10: 'CENTRO 98'
--------------------------------------------------------------------------------
Fila problemática en línea 2189
Datos obtenidos: ['CNMA 24-ANEXO PCIA STA CRUZ - EL SALVADOR', 'B° BALACCO 840', '3', '05844 a 05846', '1.035']
Error: invalid literal for int() with base 10: 'B° BALACCO 840'
--------------------------------------------------------------------------------
Fila problemática en línea 2277
Datos obtenidos: ['JARD INF JORGE A NEWBERY - ESPAÑA', 'B° SAN MARTIN 86', '4', '05932 a 05935', '1.332']
Error: invalid literal for int() with base 10: 'B° SAN MARTIN 86'
--------------------------------------------------------------------------------
Fila problemática en línea 2295
Datos obtenidos: ['ESC GUIDO SPANO - SARMIENTO', 'CENTRO 672', '8', '05955 a 05962', '2.680']
Error: invalid literal for int() with base 10: 'CENTRO 672'
--------------------------------------------------------------------------------
Fila problemática en línea 2323
Datos obtenidos: ['ESC GRAL JUSTO S ANAYA - AZOPARDO', 'FENIX 1.270', '15', '06034 a 06048', '5.175']
Error: invalid literal for int() with base 10: 'FENIX 1.270'
--------------------------------------------------------------------------------
Fila problemática en línea 2373
Datos obtenidos: ['INST JUAN BAUTISTA ALBERDI - BV LORENZO BERARDO', 'NORTE 325', '4', '06324 a 06327', '1.358']
Error: invalid literal for int() with base 10: 'NORTE 325'
--------------------------------------------------------------------------------
Fila problemática en línea 2390
Datos obtenidos: ['6.000 asociada a 6.340']
Error: list index out of range
--------------------------------------------------------------------------------
Fila problemática en línea 2490
Datos obtenidos: ['MARGARITA V LUDUEÑA DE LAZO - SARMIENTO', 'LAS MALVINAS 571', '7', '06379 a 06385', '2.373']
Error: invalid literal for int() with base 10: 'LAS MALVINAS 571'
--------------------------------------------------------------------------------
Fila problemática en línea 2627
Datos obtenidos: ['ESC JOSE DE SAN MARTIN - RIVADAVIA', 'CENTRO 768', '8', '06506 a 06513', '2.715']
Error: invalid literal for int() with base 10: 'CENTRO 768'
--------------------------------------------------------------------------------
Fila problemática en línea 3031
Datos obtenidos: ['ESC GENERAL BARTOLOME MITRE - AV JUAN PERON', 'S/N', '7', '07132 a 07138', '2.299']
Error: invalid literal for int() with base 10: 'S/N'
--------------------------------------------------------------------------------

In [30]:
print("Filas procesadas correctamente:", filas_correctas_diag)
print("Filas problemáticas:", len(filas_problematicas))
print("Discontinuidades detectadas:", len(discontinuidades_diag))
print("Última mesa encontrada:", ultima_mesa_diag)

Filas procesadas correctamente: 1164
Filas problemáticas: 51
Discontinuidades detectadas: 5
Última mesa encontrada: 8649

In [19]:
for fila in filas_problematicas:
    print("Línea:", fila["linea"])
    print("Contenido:", fila["contenido"])
    print("Separación obtenida:", fila["datos"])
    print("Error:", fila["error"])
    print("-" * 100)

Línea: 216
Contenido: ESC PETER PAN - P DE GUZMAN    B°M DE SOBREMONTE 131                             15    00802 a 00816             5.198
Separación obtenida: ['ESC PETER PAN - P DE GUZMAN', 'B°M DE SOBREMONTE 131', '15', '00802 a 00816', '5.198']
Error: invalid literal for int() with base 10: 'B°M DE SOBREMONTE 131'
----------------------------------------------------------------------------------------------------
Línea: 218
Contenido: JOSE LUIS SERCIC - PEREZ CORREA    M DE SOBREMONTE 1.500                          8    00820 a 00827             2.768
Separación obtenida: ['JOSE LUIS SERCIC - PEREZ CORREA', 'M DE SOBREMONTE 1.500', '8', '00820 a 00827', '2.768']
Error: invalid literal for int() with base 10: 'M DE SOBREMONTE 1.500'
----------------------------------------------------------------------------------------------------
Línea: 234
Contenido: ESC NACIONES UNIDAS - CTDA    8 S/N                                            9    00845 a 00853             3.096
Separación obtenida: ['ESC NACIONES UNIDAS - CTDA', '8 S/N', '9', '00845 a 00853', '3.096']
Error: invalid literal for int() with base 10: '8 S/N'
----------------------------------------------------------------------------------------------------
Línea: 241
Contenido: ESC FRANCISCO VIDAL - FRAGUEIRO     (MANZANA "C") 4.200                       12    00878 a 00889             4.062
Separación obtenida: ['ESC FRANCISCO VIDAL - FRAGUEIRO', '(MANZANA "C") 4.200', '12', '00878 a 00889', '4.062']
Error: invalid literal for int() with base 10: '(MANZANA "C") 4.200'
----------------------------------------------------------------------------------------------------
Línea: 246
Contenido: ESC   RABINDRANAT TAGORE - OCARINA    - B° V CLAUDINA 1.613                    3    00897 a 00899               784
Separación obtenida: ['ESC   RABINDRANAT TAGORE - OCARINA', '- B° V CLAUDINA 1.613', '3', '00897 a 00899', '784']
Error: invalid literal for int() with base 10: '- B° V CLAUDINA 1.613'
----------------------------------------------------------------------------------------------------
Línea: 254
Contenido: ESC FRAY J A DE SAN ALBERTO - ESQUIU    B°PUEYRREDON 1.340                     7    00912 a 00918             2.408
Separación obtenida: ['ESC FRAY J A DE SAN ALBERTO - ESQUIU', 'B°PUEYRREDON 1.340', '7', '00912 a 00918', '2.408']
Error: invalid literal for int() with base 10: 'B°PUEYRREDON 1.340'
----------------------------------------------------------------------------------------------------
Línea: 257
Contenido: INST SAGRADO CORAZON - ROMA     B°PUEYRREDON 1.153                            10    00937 a 00946             3.438
Separación obtenida: ['INST SAGRADO CORAZON - ROMA', 'B°PUEYRREDON 1.153', '10', '00937 a 00946', '3.438']
Error: invalid literal for int() with base 10: 'B°PUEYRREDON 1.153'
----------------------------------------------------------------------------------------------------
Línea: 258
Contenido: ESC ROBLES - PADRE LUIS MONTI     B°PUEYRREDON 1.850                          13    00947 a 00959             4.459
Separación obtenida: ['ESC ROBLES - PADRE LUIS MONTI', 'B°PUEYRREDON 1.850', '13', '00947 a 00959', '4.459']
Error: invalid literal for int() with base 10: 'B°PUEYRREDON 1.850'
----------------------------------------------------------------------------------------------------
Línea: 278
Contenido: ESC   RICARDO ROJAS - J.LOPEZ     B°ALTOS DE V CABRERA 2.050                   8    01028 a 01035             2.672
Separación obtenida: ['ESC   RICARDO ROJAS - J.LOPEZ', 'B°ALTOS DE V CABRERA 2.050', '8', '01028 a 01035', '2.672']
Error: invalid literal for int() with base 10: 'B°ALTOS DE V CABRERA 2.050'
----------------------------------------------------------------------------------------------------
Línea: 294
Contenido: ESC DE COMERCIO J J PASO - PLATON       B°LOS PARAISOS 3.030               10    01052 a 01061             3.440
Separación obtenida: ['ESC DE COMERCIO J J PASO - PLATON', 'B°LOS PARAISOS 3.030', '10', '01052 a 01061', '3.440']
Error: invalid literal for int() with base 10: 'B°LOS PARAISOS 3.030'
----------------------------------------------------------------------------------------------------
Línea: 297
Contenido: ESC PCIA    DE MISIONES - FIRPO 2.254                                      14    01079 a 01092             4.810
Separación obtenida: ['ESC PCIA', 'DE MISIONES - FIRPO 2.254', '14', '01079 a 01092', '4.810']
Error: invalid literal for int() with base 10: 'DE MISIONES - FIRPO 2.254'
----------------------------------------------------------------------------------------------------
Línea: 346
Contenido: ESC REPUBLICA DE SIRIA - TRAFUL     B°PQUE ATLANTICA 908                   6    01282 a 01287             2.028
Separación obtenida: ['ESC REPUBLICA DE SIRIA - TRAFUL', 'B°PQUE ATLANTICA 908', '6', '01282 a 01287', '2.028']
Error: invalid literal for int() with base 10: 'B°PQUE ATLANTICA 908'
----------------------------------------------------------------------------------------------------
Línea: 358
Contenido: IPEM 183"PEDRO B.PALACIOS" - REALICO    - 2.407                            4    01329 a 01332             1.270
Separación obtenida: ['IPEM 183"PEDRO B.PALACIOS" - REALICO', '- 2.407', '4', '01329 a 01332', '1.270']
Error: invalid literal for int() with base 10: '- 2.407'
----------------------------------------------------------------------------------------------------
Línea: 384
Contenido: ESC GDOR EMILIO OLMOS - AV FUERZA AEREA    B°PARQUE CAPITAL               10    01469 a 01478             3.380
Separación obtenida: ['ESC GDOR EMILIO OLMOS - AV FUERZA AEREA', 'B°PARQUE CAPITAL', '10', '01469 a 01478', '3.380']
Error: invalid literal for int() with base 10: 'B°PARQUE CAPITAL'
----------------------------------------------------------------------------------------------------
Línea: 406
Contenido: ESC BANDERA ARGENTINA - CASADO    STA ISABEL 1RA SECCION 634                   11    01537 a 01547             3.754
Separación obtenida: ['ESC BANDERA ARGENTINA - CASADO', 'STA ISABEL 1RA SECCION 634', '11', '01537 a 01547', '3.754']
Error: invalid literal for int() with base 10: 'STA ISABEL 1RA SECCION 634'
----------------------------------------------------------------------------------------------------
Línea: 439
Contenido: ESC PQUIAL SAN JOSE - VELEZ    B° 252                                          12    01687 a 01698             4.164
Separación obtenida: ['ESC PQUIAL SAN JOSE - VELEZ', 'B° 252', '12', '01687 a 01698', '4.164']
Error: invalid literal for int() with base 10: 'B° 252'
----------------------------------------------------------------------------------------------------
Línea: 511
Contenido: ESC REPUBLICA DE VENEZUELA - BOYERO    - 517                                  10    01977 a 01986             3.400
Separación obtenida: ['ESC REPUBLICA DE VENEZUELA - BOYERO', '- 517', '10', '01977 a 01986', '3.400']
Error: invalid literal for int() with base 10: '- 517'
----------------------------------------------------------------------------------------------------
Línea: 525
Contenido: ESC LUTERANO CONCORDIA - SANTA ANA    B°ALTO ALBERDI 2.011                    16    02051 a 02066             5.535
Separación obtenida: ['ESC LUTERANO CONCORDIA - SANTA ANA', 'B°ALTO ALBERDI 2.011', '16', '02051 a 02066', '5.535']
Error: invalid literal for int() with base 10: 'B°ALTO ALBERDI 2.011'
----------------------------------------------------------------------------------------------------
Línea: 531
Contenido: ESC EJERCITO ARGENTINO - LA RIOJA    - B° VILLA SIBURU 3.453                   8    02085 a 02092             2.752
Separación obtenida: ['ESC EJERCITO ARGENTINO - LA RIOJA', '- B° VILLA SIBURU 3.453', '8', '02085 a 02092', '2.752']
Error: invalid literal for int() with base 10: '- B° VILLA SIBURU 3.453'
----------------------------------------------------------------------------------------------------
Línea: 549
Contenido: ESC CONSTANCIO C VIGIL - J.LLERENA    - 5.561                                  8    02152 a 02159             2.718
Separación obtenida: ['ESC CONSTANCIO C VIGIL - J.LLERENA', '- 5.561', '8', '02152 a 02159', '2.718']
Error: invalid literal for int() with base 10: '- 5.561'
----------------------------------------------------------------------------------------------------
Línea: 583
Contenido: ESC MONSEÑOR M DE ANDREA - 17 DE JULIO     B°FVRO MITRE 380                    10    02265 a 02274             3.453
Separación obtenida: ['ESC MONSEÑOR M DE ANDREA - 17 DE JULIO', 'B°FVRO MITRE 380', '10', '02265 a 02274', '3.453']
Error: invalid literal for int() with base 10: 'B°FVRO MITRE 380'
----------------------------------------------------------------------------------------------------
Línea: 621
Contenido: ESC PRIMARIA CARLOS M DE ALVEA - VUCETICH    B°ITUZAINGO 6.410               7    02417 a 02423             2.429
Separación obtenida: ['ESC PRIMARIA CARLOS M DE ALVEA - VUCETICH', 'B°ITUZAINGO 6.410', '7', '02417 a 02423', '2.429']
Error: invalid literal for int() with base 10: 'B°ITUZAINGO 6.410'
----------------------------------------------------------------------------------------------------
Línea: 641
Contenido: ESC ARISTOBULO DEL VALLE - M DE JAUREGUI    B°L N ALEM 1.657                10    02502 a 02511             3.430
Separación obtenida: ['ESC ARISTOBULO DEL VALLE - M DE JAUREGUI', 'B°L N ALEM 1.657', '10', '02502 a 02511', '3.430']
Error: invalid literal for int() with base 10: 'B°L N ALEM 1.657'
----------------------------------------------------------------------------------------------------
Línea: 642
Contenido: ESC ASOCIACION DE MAYO - COLOMPREA    B° ALEM 1.500                          5    02512 a 02516             1.715
Separación obtenida: ['ESC ASOCIACION DE MAYO - COLOMPREA', 'B° ALEM 1.500', '5', '02512 a 02516', '1.715']
Error: invalid literal for int() with base 10: 'B° ALEM 1.500'
----------------------------------------------------------------------------------------------------
Línea: 711
Contenido: ESC A CAPDEVILA/ DR. B HOUSEY - A CAPDEVILA    Y BILIBISACATE 709              11    02768 a 02778             3.817
Separación obtenida: ['ESC A CAPDEVILA/ DR. B HOUSEY - A CAPDEVILA', 'Y BILIBISACATE 709', '11', '02768 a 02778', '3.817']
Error: invalid literal for int() with base 10: 'Y BILIBISACATE 709'
----------------------------------------------------------------------------------------------------
Línea: 712
Contenido: ESC CURA BROCHERO - JAMAICA    B°RESID AMERICA 967                             12    02779 a 02790             4.164
Separación obtenida: ['ESC CURA BROCHERO - JAMAICA', 'B°RESID AMERICA 967', '12', '02779 a 02790', '4.164']
Error: invalid literal for int() with base 10: 'B°RESID AMERICA 967'
----------------------------------------------------------------------------------------------------
Línea: 715
Contenido: ESC JUSTO PAEZ MOLINA - J MONTAÑO    B° VILLA AZALAIZ 1.350                    14    02811 a 02824             4.858
Separación obtenida: ['ESC JUSTO PAEZ MOLINA - J MONTAÑO', 'B° VILLA AZALAIZ 1.350', '14', '02811 a 02824', '4.858']
Error: invalid literal for int() with base 10: 'B° VILLA AZALAIZ 1.350'
----------------------------------------------------------------------------------------------------
Línea: 716
Contenido: ESC VICENTE F LOPEZ - TISSERA    B° L N ALEM 1.551                             15    02825 a 02839             5.205
Separación obtenida: ['ESC VICENTE F LOPEZ - TISSERA', 'B° L N ALEM 1.551', '15', '02825 a 02839', '5.205']
Error: invalid literal for int() with base 10: 'B° L N ALEM 1.551'
----------------------------------------------------------------------------------------------------
Línea: 727
Contenido: ESC MUNIC J A PAREDES - FCO DEL PRADO    V AZALAIS 3.900                   8    02840 a 02847             2.776
Separación obtenida: ['ESC MUNIC J A PAREDES - FCO DEL PRADO', 'V AZALAIS 3.900', '8', '02840 a 02847', '2.776']
Error: invalid literal for int() with base 10: 'V AZALAIS 3.900'
----------------------------------------------------------------------------------------------------
Línea: 787
Contenido: ESC JUAN ZORRILA DE SAN MARTIN - JOSE E BUSTOS     C DE LAS ROSAS 1.875          11    03016 a 03026             3.624
Separación obtenida: ['ESC JUAN ZORRILA DE SAN MARTIN - JOSE E BUSTOS', 'C DE LAS ROSAS 1.875', '11', '03016 a 03026', '3.624']
Error: invalid literal for int() with base 10: 'C DE LAS ROSAS 1.875'
----------------------------------------------------------------------------------------------------
Línea: 818
Contenido: ESC   REPUBLICA DE PANAMA - TRECE BIS    COL   DEL CERRO                          7    03125 a 03131             2.352
Separación obtenida: ['ESC   REPUBLICA DE PANAMA - TRECE BIS', 'COL   DEL CERRO', '7', '03125 a 03131', '2.352']
Error: invalid literal for int() with base 10: 'COL   DEL CERRO'
----------------------------------------------------------------------------------------------------
Línea: 860
Contenido: ESC MUNIC DR JORGE ORGAZ - LAGUNA LARGA/R LUNA     V R INDARTE                       7    03240 a 03246             2.257
Separación obtenida: ['ESC MUNIC DR JORGE ORGAZ - LAGUNA LARGA/R LUNA', 'V R INDARTE', '7', '03240 a 03246', '2.257']
Error: invalid literal for int() with base 10: 'V R INDARTE'
----------------------------------------------------------------------------------------------------
Línea: 1113
Contenido: ESC CIUDAD DE MALVINAS ARGENT. - AV SAN MARTIN     2°SECC. 600                12    03742 a 03753             4.152
Separación obtenida: ['ESC CIUDAD DE MALVINAS ARGENT. - AV SAN MARTIN', '2°SECC. 600', '12', '03742 a 03753', '4.152']
Error: invalid literal for int() with base 10: '2°SECC. 600'
----------------------------------------------------------------------------------------------------
Línea: 1213
Contenido:                                                                                         4.077 asociada a 4.076
Separación obtenida: ['4.077 asociada a 4.076']
Error: list index out of range
----------------------------------------------------------------------------------------------------
Línea: 1493
Contenido:                                                                                  4.392 asociada a 4.390
Separación obtenida: ['4.392 asociada a 4.390']
Error: list index out of range
----------------------------------------------------------------------------------------------------
Línea: 1494
Contenido:                                                                                  4.393 asociada a 4.391
Separación obtenida: ['4.393 asociada a 4.391']
Error: list index out of range
----------------------------------------------------------------------------------------------------
Línea: 1579
Contenido: ESC.M.J.G.DE BELGRANO - JERONIMO L DE CABRERA     L ALGARROBOS 451                     10    04678 a 04687             3.450
Separación obtenida: ['ESC.M.J.G.DE BELGRANO - JERONIMO L DE CABRERA', 'L ALGARROBOS 451', '10', '04678 a 04687', '3.450']
Error: invalid literal for int() with base 10: 'L ALGARROBOS 451'
----------------------------------------------------------------------------------------------------
Línea: 1819
Contenido: ESC MARIANO MORENO - SAN JUAN    SUR 1.090                                         8    05123 a 05130             2.742
Separación obtenida: ['ESC MARIANO MORENO - SAN JUAN', 'SUR 1.090', '8', '05123 a 05130', '2.742']
Error: invalid literal for int() with base 10: 'SUR 1.090'
----------------------------------------------------------------------------------------------------
Línea: 1820
Contenido: ESCUELA BARTOLOME MITRE - HIPOLITO YRIGOYEN    NOROESTE 1.409                      7    05131 a 05137             2.394
Separación obtenida: ['ESCUELA BARTOLOME MITRE - HIPOLITO YRIGOYEN', 'NOROESTE 1.409', '7', '05131 a 05137', '2.394']
Error: invalid literal for int() with base 10: 'NOROESTE 1.409'
----------------------------------------------------------------------------------------------------
Línea: 2068
Contenido: INST ALFONSINA STORNI(EX IESS) - SOLIS    B° VILLA DOMINGUEZ 283                 21    05477 a 05497             7.266
Separación obtenida: ['INST ALFONSINA STORNI(EX IESS) - SOLIS', 'B° VILLA DOMINGUEZ 283', '21', '05477 a 05497', '7.266']
Error: invalid literal for int() with base 10: 'B° VILLA DOMINGUEZ 283'
----------------------------------------------------------------------------------------------------
Línea: 2164
Contenido: INSTITUTO ADELIA MARIA - AV SAN MARTIN     CENTRO 1.050                              11    05713 a 05723             3.740
Separación obtenida: ['INSTITUTO ADELIA MARIA - AV SAN MARTIN', 'CENTRO 1.050', '11', '05713 a 05723', '3.740']
Error: invalid literal for int() with base 10: 'CENTRO 1.050'
----------------------------------------------------------------------------------------------------
Línea: 2165
Contenido: ESC GENERAL SAN MARTIN - SARMIENTO     CENTRO 98                                      8    05724 a 05731             2.713
Separación obtenida: ['ESC GENERAL SAN MARTIN - SARMIENTO', 'CENTRO 98', '8', '05724 a 05731', '2.713']
Error: invalid literal for int() with base 10: 'CENTRO 98'
----------------------------------------------------------------------------------------------------
Línea: 2189
Contenido: CNMA 24-ANEXO PCIA STA CRUZ - EL SALVADOR    B° BALACCO 840                           3    05844 a 05846             1.035
Separación obtenida: ['CNMA 24-ANEXO PCIA STA CRUZ - EL SALVADOR', 'B° BALACCO 840', '3', '05844 a 05846', '1.035']
Error: invalid literal for int() with base 10: 'B° BALACCO 840'
----------------------------------------------------------------------------------------------------
Línea: 2277
Contenido: JARD INF JORGE A NEWBERY - ESPAÑA    B° SAN MARTIN 86                        4    05932 a 05935             1.332
Separación obtenida: ['JARD INF JORGE A NEWBERY - ESPAÑA', 'B° SAN MARTIN 86', '4', '05932 a 05935', '1.332']
Error: invalid literal for int() with base 10: 'B° SAN MARTIN 86'
----------------------------------------------------------------------------------------------------
Línea: 2295
Contenido: ESC GUIDO SPANO - SARMIENTO    CENTRO 672                                    8    05955 a 05962             2.680
Separación obtenida: ['ESC GUIDO SPANO - SARMIENTO', 'CENTRO 672', '8', '05955 a 05962', '2.680']
Error: invalid literal for int() with base 10: 'CENTRO 672'
----------------------------------------------------------------------------------------------------
Línea: 2323
Contenido: ESC GRAL JUSTO S ANAYA - AZOPARDO    FENIX 1.270                          15    06034 a 06048             5.175
Separación obtenida: ['ESC GRAL JUSTO S ANAYA - AZOPARDO', 'FENIX 1.270', '15', '06034 a 06048', '5.175']
Error: invalid literal for int() with base 10: 'FENIX 1.270'
----------------------------------------------------------------------------------------------------
Línea: 2373
Contenido: INST JUAN BAUTISTA ALBERDI - BV LORENZO BERARDO    NORTE 325                       4      06324 a 06327             1.358
Separación obtenida: ['INST JUAN BAUTISTA ALBERDI - BV LORENZO BERARDO', 'NORTE 325', '4', '06324 a 06327', '1.358']
Error: invalid literal for int() with base 10: 'NORTE 325'
----------------------------------------------------------------------------------------------------
Línea: 2390
Contenido:                                                                                         6.000 asociada a 6.340
Separación obtenida: ['6.000 asociada a 6.340']
Error: list index out of range
----------------------------------------------------------------------------------------------------
Línea: 2490
Contenido: MARGARITA V LUDUEÑA DE LAZO - SARMIENTO    LAS MALVINAS 571                  7    06379 a 06385             2.373
Separación obtenida: ['MARGARITA V LUDUEÑA DE LAZO - SARMIENTO', 'LAS MALVINAS 571', '7', '06379 a 06385', '2.373']
Error: invalid literal for int() with base 10: 'LAS MALVINAS 571'

#Dataframe

In [31]:
df_escuelas = pd.DataFrame(escuelas)

display(df_escuelas.head())
display(df_escuelas.tail())

print(df_escuelas.shape)

,seccion_nro,seccion_name,circuito_nro,circuito_name,establecimiento,cant_mesas,desde,hasta,electores
0,1,CAPITAL,1,SECCIONAL PRIMERA,CENTRO EDUC.NIVEL MEDIO ADULTO - DEAN FUNES 417,7,1,7,2401
1,1,CAPITAL,1,SECCIONAL PRIMERA,ESC NUESTRA SEÑORA DEL HUERTO - BELGRANO 269,12,8,19,4116
2,1,CAPITAL,1,SECCIONAL PRIMERA,COL NAC DE MONSERRAT - OBISPO TREJO 294,18,20,37,6158
3,1,CAPITAL,1,SECCIONAL PRIMERA,ESC SANTA TERESA DE JESUS - OBISPO TREJO Y SAN...,10,38,47,3420
4,1,CAPITAL,2,SECCIONAL SEGUNDA,ESC JUAN BAUTISTA ALBERDI - GRAL PAZ 486,18,48,65,6145

,seccion_nro,seccion_name,circuito_nro,circuito_name,establecimiento,cant_mesas,desde,hasta,electores
1206,26,UNION,397A,CORRAL DEL BAJO,ESCUELA VALENTIN ALSINA - CORRAL DEL BAJO,1,8634,8634,7
1207,26,UNION,400,SAN MARCOS SUD,INST JOSE DE SAN MARTIN - SAN MARCOS SUD,5,8635,8639,1570
1208,26,UNION,400,SAN MARCOS SUD,ESC PROV M BUCHARDO - SAN MARCOS SUD,4,8640,8643,1253
1209,26,UNION,401,SANTA MARIA,ESC PROV PAULA ALBARRACIN - PUBLICA S/N,1,8644,8644,226
1210,26,UNION,402,VIAMONTE,INSTITUTO JUAN B ALBERDI - AVELLANEDA 182,5,8645,8649,1599

(1211, 9)

In [ ]:
df_escuelas.sample(20, random_state=42)

,seccion_nro,seccion_name,circuito_nro,circuito_name,establecimiento,cant_mesas,desde,hasta,electores
319,1,CAPITAL,14F,GRANJA DE FUNES,ESC JAVIER LAZCANO COLODRERO - CARLOS BROGGI S...,9,2989,2997,3015
956,20,SAN JUSTO,281,BEIRO,ESCUELA N°349(ESC JUAN BEIRO) - BEIRO,1,7039,7039,155
1181,26,UNION,400,SAN MARCOS SUD,INST JOSE DE SAN MARTIN - SAN MARCOS SUD,4,8398,8401,1380
86,1,CAPITAL,7G,PANAMERICANO,"ESC FRANCISCO VIDAL - FRAGUEIRO (MANZANA ""C""...",12,857,868,4097
990,20,SAN JUSTO,302,MAUNIER,ESC PROV GRAL SAN MARTIN - PUBLICA S/N,1,7214,7214,113
458,4,CRUZ DEL EJE,45,EL BRETE,ESC PROV MANUEL BELGRANO - PUBLICA S/N,4,4030,4033,1172
1035,21,SANTA MARIA,316,ALTA GRACIA,ESC SANTIAGO DE LINIERS - B°LINIERS,8,7590,7597,2744
946,20,SAN JUSTO,278,ALTOS DE CHIPION,ESC.PROV.RECONQUISTA - SARMIENTO 543,6,6956,6961,1853
323,1,CAPITAL,14H,MERCANTIL,ESC ARTEMIO ARAN - PUBLICA ESQ JACINTO YABEN,6,3025,3030,1968
361,2,CALAMUCHITA,20A,VILLA GENERAL BELGRANO,ESC.GRAL J. DE SAN MARTIN - VILLA GRAL.BELGRANO,9,3234,3242,3069
220,1,CAPITAL,12,AVELLANEDA,ESC MUNIC OSCAR SOTO LOPEZ - LOS ALGARROBOS/ES...,6,2112,2117,2004
1052,21,SANTA MARIA,323,DESPEÑADEROS,INSTITUTO PRIVADO PIO XII - PADRE BUTELER 229,10,7649,7658,3300
1137,25,TULUMBA,370,SANTA CRUZ,ESC PROV CORNELIO SAAVEDRA - PUBLICA S/N,1,8128,8128,97
713,13,RIO CUARTO,162,ALCIRA,ESC PERITO FRANCISCO MORENO - DEAN FUNES Y HER...,9,5576,5584,3096
243,1,CAPITAL,12F,JOSE HERNANDEZ,ESC MUNIC BRIG JUAN I DE S MAR - BRAGADO/TRENQ...,7,2312,2318,2415
170,1,CAPITAL,11A,ALTO ALBERDI,ESC PQUIAL SAN JOSE - VELEZ 252 B° ALTO ALBERDI,12,1651,1662,4092
274,1,CAPITAL,13F,NUEVA ITALIA,ESC MODELO RACING - TREDENTINA B°NUEVA ITALI...,11,2559,2569,3740
1089,23,TERCERO ARRIBA,343,LOS ZORROS,ESC VICENTE LOPEZ Y PLANES - SAN MARTIN 346,2,7859,7860,603
858,16,RIO SEGUNDO,239,ONCATIVO,ESC JOSE MARIA PAZ - ONCATIVO,12,6418,6429,4110
665,12,PUNILLA,152A,VILLA GIARDINO,IPEM N° 339 - LOS COCOS ESQ PEPERINA,6,5202,5207,2000

In [32]:
output_path = "escuelas-elecciones-2017-cordoba.csv"

df_escuelas.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print(f"Archivo exportado: {output_path}")

Archivo exportado: escuelas-elecciones-2015-cordoba.csv